export { copysign } from "./copysign.ts";
export { fabs } from "./fabs.ts";
export { fpclassify } from "./fpclassify.ts";
export { frexp, type FrexpResult } from "./frexp.ts";
export { hypot } from "./hypot.ts";
export { iscanonical } from "./iscanonical.ts";
export { ldexp } from "./ldexp.ts";
export * from "./macros.ts";
export { nan } from "./nan.ts";
export { nextafter } from "./nextafter.ts";
export { pow } from "./pow.ts";
