name: "Publish to NPM if package.json's \"version\" field was updated"
on:
  workflow_run:
    branches: [ "main" ]
    types: [ "completed" ]
    workflows: [ "Verify: Test, lint, and typecheck" ]

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.checkpublish.outputs.exists }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Get the version from package.json and check if it has been published already"
        id: checkpublish
        uses: tehpsalmist/npm-publish-status-action@v1

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: check-if-published-already
    if: needs.check.outputs.exists == '0' # Do not run if NPM already has this version
    steps:
      - name: "Log in to DockerHub"
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: "Build an image containing everything needed for building and publishing the library"
        run: docker compose -f ci-publish.docker-compose.yml build

      - name: "Publish the library"
        run: docker compose -f ci-publish.docker-compose.yml run ci-publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

permissions:
  id-token: write # Needed for provenance
