name: "Check that the package is available on npmjs.com"
on:
  schedule:
    - cron: "17 */3 * * *"

jobs:
  check_availability:
    name: "Install package"
    runs-on: ubuntu-latest
    steps:
      - name: "Install NPM"
        uses: actions/setup-node@v6
        with:
          node-version: latest
      - name: "Install package"
        run: npm install cmath-js --prefer-online --cache ./cache
