name: "Verify: Test, lint, and typecheck"
on: [ "pull_request", "push" ]
jobs:
  verify:
    name: "Verify"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Build image needed for verification"
        run: docker compose -f ci-verify.docker-compose.yml build

      - name: "Verify"
        run: docker compose -f ci-verify.docker-compose.yml run --rm ci-verify
