name: "Verify: Test, lint, and typecheck"
on: [ "pull_request", "push" ]
jobs:
  verify:
    name: "Verify"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: Check if the DockerHub secrets are available
        id: dockerhub-secrets-check
        shell: bash
        run: |
          if [ "${{ secrets.DOCKERHUB_USERNAME }}" = '' ]; then
            echo "available=0" >> $GITHUB_OUTPUT;
          else
            echo "available=1" >> $GITHUB_OUTPUT;
          fi

      - name: "DockerHub Login"
        if: ${{ steps.dockerhub-secrets-check.available != '0' }}
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: "Build image needed for verification"
        run: docker compose -f ci-verify.docker-compose.yml build

      - name: "Verify"
        run: docker compose -f ci-verify.docker-compose.yml run --rm ci-verify
